language: node_js

node_js:
  - "8"
cache:
  directories:
  - node_modules
env:
  - OUTPUT_MODULE=commonjs
script:
  - npm run build
  - npm run pubdocs 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs/build
  on:
    branch: master
  
