sudo: false
language: node_js

node_js:
  - "8"
cache:
  directories:
  - node_modules
env:
  - OUTPUT_MODULE=commonjs
before_script : "npm run test -- -u"

script: 
  - npm run lint
  - npm run test

after_script: 
  - npm run ci:coverage
